```{python}
import numpy as np
from matplotlib import pyplot as plt
import quantities as pq
from neo.core import AnalogSignal
from elephant.spike_train_generation import StationaryPoissonProcess, NonStationaryPoissonProcess
from elephant.statistics import mean_firing_rate, time_histogram, isi, cv
np.random.seed(8)
```

Simulate a stationary poisson Process 
```{python}
rate =  0.1 * pq.Hz
t_start = 0 * pq.s
t_stop = 10 * pq.s
neuron1 = StationaryPoissonProcess(rate=rate, t_start=t_start, t_stop=t_stop)
```

```{python}
n_spikes = []
for i in range(1000):
    spike_train = neuron1.generate_spiketrain()
    n_spikes.append(len(spike_train))
plt.hist(n_spikes)
plt.xlabel("Spike Count")
plt.ylabel("Number of Observations")
```


Simulate a stationary poisson Process 
```{python}
rate =  5 * pq.Hz
t_start = 0 * pq.s
t_stop = 20 * pq.s
neuron1 = StationaryPoissonProcess(rate=rate, t_start=t_start, t_stop=t_stop)
```

Observe the number of spikes across multiple time intervals
```{python}
# plot theoretical poisson distribution
n_spikes = []
for i in range(1000):
    spike_train = neuron1.generate_spiketrain()
    n_spikes.append(len(spike_train))
plt.hist(n_spikes)
plt.xlabel("Spike Count")
plt.ylabel("Number of Observations")
```

Plot the distribution of intervals for a single spike train
```{python}
spike_train = neuron1.generate_spiketrain()
inter_spike_intervals = isi(spike_train)
plt.hist(inter_spike_intervals.magnitude)
plt.xlabel("Spike Count")
plt.ylabel("Number of Observations")
```

Compute the coefficient of variation (CV) for multiple spike trains and plot the distribution
```{python}
# what would be the expected distribution
# How do we arrive at CV=1 for the poisson
coefficient_of_variation = []
for i in range(1000):
    spike_train = neuron1.generate_spiketrain()
    inter_spike_intervals = isi(spike_train)
    coefficient_of_variation.append(cv(inter_spike_intervals))
plt.hist(coefficient_of_variation)
plt.xlabel("Coefficient of Variation")
plt.ylabel("Number of Observations")
```

We can also add a refractory period to the neuron. This makes firing more regular and less Poisson-like.
```{python}
neuron2 = StationaryPoissonProcess(rate=rate, t_start=t_start, t_stop=t_stop, refractory_period=2*pq.ms)
coefficient_of_variation = []
for i in range(1000):
    spike_train = neuron2.generate_spiketrain()
    inter_spike_intervals = isi(spike_train)
    coefficient_of_variation.append(cv(inter_spike_intervals))
plt.hist(coefficient_of_variation)
plt.axvline(x=1, ymin=0, ymax=1, linestyle='--', color="black")
plt.xlabel("Coefficient of Variation")
plt.ylabel("Number of Observations")
```

Often, neurons do not behave as poisson processes because their firing depends on perceptual, cognitive or motor events. We can simulate this as a `NonStationaryPoissonProcess` with a firing rate that varies over time. First, we generate the time-varying rate as an `AnalogSignal`.

```{python}
# How do we reverse the process - estimating the time-varying firing rate from the observed spikes?
t_start = 0 * pq.s
t_stop = 5 * pq.s
modulation_amplitude = 10 * pq.Hz
modulation_rate = 0.5 * pq.Hz
sampling_rate = 1000 * pq.Hz
duration = t_stop - t_start
n_samples = int(duration * sampling_rate)
t = np.linspace(t_start, t_stop, n_samples)
signal = modulation_amplitude*np.sin(2*np.pi*modulation_rate*t)
signal += modulation_amplitude
plt.plot(t, signal)
```

Create an `AnalogSignal` and use it as a time-varying `rate_signal` for the `NonStationaryPoissonProcess`
```{python}
rate_signal = AnalogSignal(
    signal=signal,
    sampling_rate=sampling_rate,
    t_start=t_start,
    t_stop=t_stop,
    )
neuron3 = NonStationaryPoissonProcess(rate_signal=rate_signal)
```

Plot the modulation frequency together with the spike times
```{python}
fig, ax = plt.subplots(2, sharex=True)
spike_times = neuron3.generate_spiketrain().times
ax[0].plot(rate_signal.times, rate_signal)
ax[1].eventplot(spike_times)
```

Plot the cv distribution for this bursting neuron
```{python}
coefficient_of_variation = []
for i in range(1000):
    spike_train = neuron3.generate_spiketrain()
    inter_spike_intervals = isi(spike_train)
    coefficient_of_variation.append(cv(inter_spike_intervals))
plt.hist(coefficient_of_variation)
plt.axvline(x=1, ymin=0, ymax=1, linestyle='--', color="black")
plt.xlabel("Coefficient of Variation")
plt.ylabel("Number of Observations")
```

```{python}
# estimate chi^2?
```



